---
info:
  title: Jfixtures
  x-cortex-git:
    github:
      alias: intsightsorg
      repository: Intsights/jfixtures
  x-cortex-tag: jfixtures
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: threatintel-platform-delivery
  x-cortex-groups:
  - exposure:opensource
  - target:not-deployed
openapi: 3.0.1
servers:
- url: "/"
